# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='actor.proto',
  package='actor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61\x63tor.proto\x12\x05\x61\x63tor\",\n\x0c\x41\x63torMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\"6\n\x10\x41\x63torMessageList\x12\"\n\x05\x61\x63tor\x18\x01 \x03(\x0b\x32\x13.actor.ActorMessage\"\x07\n\x05\x45mpty2v\n\x0c\x41\x63torService\x12\x30\n\x07\x66indAll\x12\x0c.actor.Empty\x1a\x17.actor.ActorMessageList\x12\x34\n\x08\x61\x64\x64\x41\x63tor\x12\x13.actor.ActorMessage\x1a\x13.actor.ActorMessageb\x06proto3'
)




_ACTORMESSAGE = _descriptor.Descriptor(
  name='ActorMessage',
  full_name='actor.ActorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='actor.ActorMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='actor.ActorMessage.gender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=66,
)


_ACTORMESSAGELIST = _descriptor.Descriptor(
  name='ActorMessageList',
  full_name='actor.ActorMessageList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='actor', full_name='actor.ActorMessageList.actor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=122,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='actor.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=131,
)

_ACTORMESSAGELIST.fields_by_name['actor'].message_type = _ACTORMESSAGE
DESCRIPTOR.message_types_by_name['ActorMessage'] = _ACTORMESSAGE
DESCRIPTOR.message_types_by_name['ActorMessageList'] = _ACTORMESSAGELIST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActorMessage = _reflection.GeneratedProtocolMessageType('ActorMessage', (_message.Message,), {
  'DESCRIPTOR' : _ACTORMESSAGE,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:actor.ActorMessage)
  })
_sym_db.RegisterMessage(ActorMessage)

ActorMessageList = _reflection.GeneratedProtocolMessageType('ActorMessageList', (_message.Message,), {
  'DESCRIPTOR' : _ACTORMESSAGELIST,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:actor.ActorMessageList)
  })
_sym_db.RegisterMessage(ActorMessageList)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'actor_pb2'
  # @@protoc_insertion_point(class_scope:actor.Empty)
  })
_sym_db.RegisterMessage(Empty)



_ACTORSERVICE = _descriptor.ServiceDescriptor(
  name='ActorService',
  full_name='actor.ActorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=133,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='findAll',
    full_name='actor.ActorService.findAll',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACTORMESSAGELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='addActor',
    full_name='actor.ActorService.addActor',
    index=1,
    containing_service=None,
    input_type=_ACTORMESSAGE,
    output_type=_ACTORMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTORSERVICE)

DESCRIPTOR.services_by_name['ActorService'] = _ACTORSERVICE

# @@protoc_insertion_point(module_scope)
